"use client"

import { useEffect, useState } from "react"
import { Textarea } from "@workspace/ui/components/textarea"
import type { ArtifactData } from "./artifact-viewer"

interface PlainTextEditorProps {
  artifact: ArtifactData | null
}

export function PlainTextEditor({ artifact }: PlainTextEditorProps) {
  const [text, setText] = useState("")

  useEffect(() => {
    if (artifact) {
      const data = artifact.data as { content?: string; text?: string; markdown?: string }
      setText(data.content ?? data.text ?? data.markdown ?? "")
    } else {
      setText("")
    }
  }, [artifact])

  return (
    <div className="flex-1 overflow-y-auto p-6">
      <Textarea
        className="min-h-[300px] resize-none border-0 bg-transparent text-base shadow-none focus-visible:ring-0"
        placeholder="Content will appear here when generated by the AI agent..."
        value={text}
        readOnly
      />
    </div>
  )
}
